version: "3.3"

services:
  traefik_reverseproxy:
    container_name:  traefik_rp
    image:           traefik:v2.0
    command:
      -              --entrypoints.web.address=:80
      -              --entrypoints.websecure.address=:443
      -              --providers.docker
      -              --api.insecure
      -              --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      -              --certificatesresolvers.leresolver.acme.email=you@example.com
      -              --certificatesresolvers.leresolver.acme.storage=/acme.json
      -              --certificatesresolvers.leresolver.acme.tlschallenge=true
    ports:
      -              8080:8080
      -               443:443
      -                80:80
    volumes:
      -              /var/run/docker.sock:/var/run/docker.sock
      -              ./acme.json:/acme.json
    networks:
      -              sh_trfk

  whoami:
    image:           containous/whoami
    labels:
      -              "traefik.frontend.rule=PathPrefixStrip:/whoami"
      -              "traefik.backend=whoami"
      -              "traefik.enable=true"
      -              "traefik.passHostHeader=true"
      -              "traefik.frontend.redirect.regex=^(.*)/whoami$$"
      -              "traefik.frontend.redirect.replacement=$$1/whoami/"
      -              "traefik.frontend.rule=PathPrefix:/whoami;ReplacePathRegex: ^/whoami/(.*) /$$1"
    networks:
      -              sh_trfk

  tomcat:
    container_name:  tom
    hostname:        tom
    build:           ./dockerfiles/tom
    ports:
      -              9081:80
    labels:
      -              "traefik.http.routers.tomcat.rule=PathPrefix(`/tom`)"
      -              "traefik.http.middlewares.theTomStrip.stripprefix.prefixes=/tom"
      -              "traefik.http.routers.tomcat.middlewares=theTomStrip"
    networks:
      -              sh_trfk


networks:
  sh_trfk: